---
- name: "Snappy: Install BIRD"
  ansible.builtin.import_tasks: bird.yml
  tags:
    - bird
    - bgp

- name: "Snappy: Speedtest"
  ansible.builtin.import_tasks: speedtest.yml
  tags:
    - speedtest

- name: "Snappy: Nginx + TLS"
  ansible.builtin.import_tasks: nginx.yml
  tags:
    - nginx

- name: "Snappy: Firewall"
  ansible.builtin.import_tasks: firewall.yml
  tags:
    - firewall
